site:
  title: Cluster-API
  url: /
  start_page: v0.21@cluster-api:en:index.adoc

content:
  sources:
    - url: ./
      start_paths: [product-docs/v0.21, product-docs/v0.20, product-docs/v0.19, product-docs/v0.18, product-docs/v0.17, product-docs/v0.16, product-docs/v0.15, product-docs/v0.14, product-docs/v0.13, product-docs/v0.12, product-docs/v0.11]
      branches: HEAD

# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site